/* eslint-disable no-constant-binary-expression */
import React, { useRef } from "react";
import { Modal, Button, Row, Col, Table } from "react-bootstrap";
import { FaFileInvoice, FaDownload } from "react-icons/fa6";
import jsPDF from "jspdf";
import html2canvas from "html2canvas";

interface InvoiceModalProps {
  show: boolean;
  handleClose: () => void;
  trip: {
    tripId?: string;
    customerName?: string;
    driver?: string;
    receivedVia?: string;
    fromDate?: string;
    toDate?: string;
    pickupFrom?: string;
    dropLocations?: string[];
    paymentMode?: string;
    paymentDetails?: string;
    details?: string;
    invoiceId?: string;
    invoiceNum?: string;
    financialYearId?: string;
    companyId?: string;
    totalAmount?: number;
    createdOn?: string;
  } | null; 
}

const InvoiceMaster: React.FC<InvoiceModalProps> = ({ show, handleClose, trip  }) => {
  const invoiceRef = useRef<HTMLDivElement>(null);
  

   // Helper function for date formatting
  const formatDate = (dateString?: string) => {
    if (!dateString) return "-";
    const date = new Date(dateString);
    if (isNaN(date.getTime())) return "-";
    return date.toLocaleDateString("en-GB", {
      day: "2-digit",
      month: "long",
      year: "numeric",
    });
  };

  const handleDownloadPDF = async () => {
    if (!invoiceRef.current) return;
    const canvas = await html2canvas(invoiceRef.current, { scale: 2 });
    const imgData = canvas.toDataURL("image/png");
    const pdf = new jsPDF("p", "mm", "a4");
    const pdfWidth = pdf.internal.pageSize.getWidth();
    const pdfHeight = (canvas.height * pdfWidth) / canvas.width;
    pdf.addImage(imgData, "PNG", 0, 0, pdfWidth, pdfHeight);
    pdf.save(`${trip?.invoiceNum || trip?.tripId || "invoice"}.pdf`);
  };

  return (
    <Modal show={show} onHide={handleClose} size="lg" centered backdrop="static">
      <Modal.Header
        closeButton
        style={{ backgroundColor: "#18575A", color: "white" }}
      >
        <Modal.Title className="d-flex align-items-center gap-2 fs-5">
          <FaFileInvoice /> Trip Invoice
        </Modal.Title>
      </Modal.Header>

      <Modal.Body ref={invoiceRef} style={{ fontFamily: "Urbanist" }} className="p-5">
        {/* Invoice Header */}
        <div className="text-center mb-4">
          <h5 className="fw-semibold mb-0" style={{ color: "#18575A" }}>
            MOVEIQ SERVICE INVOICE
          </h5>
          <small className="text-muted">Generated by MoveIQ</small>
        </div>

        {/* Invoice Info */}
        <Row className="mb-3">
          <Col md={6}>
            {/* <h6 className="fw-semibold" style={{ color: "#18575A" }}>
              Invoice ID:
            </h6> */}
             <h6 className="fw-semibold" style={{ color: "#18575A" }}>
              Invoice Number:
            </h6>
            <p className="text-muted mb-0">{`INV${trip?.tripId} `|| "-"}</p>
          </Col>
          <Col md={6}>
           <h6 className="fw-semibold" style={{ color: "#18575A" }}>
              Date:
            </h6>
            {/* <p className="text-muted mb-0">{new Date().toLocaleDateString()}</p> */}
             <p className="text-muted mb-0">{formatDate(new Date().toISOString())}</p>
            {/* <p className="text-muted mb-0">{trip?.createdOn || "-"}</p> */}
          </Col>
        </Row>

        <Row className="mb-3">
          <Col md={6}>
            <h6 className="fw-semibold" style={{ color: "#18575A" }}>
              Company Name:
            </h6>
            <p className="text-muted mb-0">{trip?.companyId || "15"}</p>
          </Col>
          <Col md={6}>
            <h6 className="fw-semibold" style={{ color: "#18575A" }}>
              Financial Year:
            </h6>
            <p className="text-muted mb-0">{trip?.financialYearId || "2025"}</p>
          </Col>
        </Row>

       

        {/* Customer Info */}
        <Row className="mb-4">
          <Col md={6}>
            <h6 className="fw-semibold" style={{ color: "#18575A" }}>
              Customer Name:
            </h6>
            <p className="text-muted mb-0">{trip?.customerName || "-"}</p>
          </Col>
          <Col md={6}>
            <h6 className="fw-semibold" style={{ color: "#18575A" }}>
              Driver:
            </h6>
            <p className="text-muted mb-0">{trip?.driver || "-"}</p>
          </Col>
        </Row>

        {/* Trip Summary */}
        <Table bordered hover size="sm" responsive>
          <tbody>
            {/* <tr>
              <th style={{ backgroundColor: "#f8f9fa" }}>Trip ID</th>
              <td>{trip?.tripId}</td>
            </tr> */}
            <tr>
              <th style={{ backgroundColor: "#f8f9fa" }}>Pickup From</th>
              <td>{trip?.pickupFrom}</td>
            </tr>
            {trip?.dropLocations && trip.dropLocations.length > 0 && (
              <tr>
                <th style={{ backgroundColor: "#f8f9fa" }}>Drop Locations</th>
                <td>{trip.dropLocations.join(", ")}</td>
              </tr>
            )}
            <tr>
              <th style={{ backgroundColor: "#f8f9fa" }}>Start Date & Time</th>
              {/* <td>{trip?.fromDate}</td> */}
               {/* Formatted Start Date */}
              <td>{formatDate(trip?.fromDate)}</td>
            </tr>
            <tr>
              <th style={{ backgroundColor: "#f8f9fa" }}>End Date & Time</th>
              {/* <td>{trip?.toDate}</td> */}
               {/* Formatted End Date */}
              <td>{formatDate(trip?.toDate)}</td>
            </tr>
            <tr>
              <th style={{ backgroundColor: "#f8f9fa" }}>Received Via</th>
              <td>{trip?.receivedVia}</td>
            </tr>
            <tr>
              <th style={{ backgroundColor: "#f8f9fa" }}>Payment Mode</th>
              <td>{trip?.paymentMode || "-"}</td>
            </tr>
            <tr>
              <th style={{ backgroundColor: "#f8f9fa" }}>Payment Details</th>
              <td>{trip?.paymentDetails || "-"}</td>
            </tr>
            {trip?.details && (
              <tr>
                <th style={{ backgroundColor: "#f8f9fa" }}>Additional Info</th>
                <td>{trip.details}</td>
              </tr>
            )}
          </tbody>
        </Table>

        {/* Signature Area */}
        <div className="mt-5 d-flex justify-content-between align-items-center">
          <div>
             <h6 className="fw-semibold" style={{ color: "#18575A" }}>
                Total Amount:
              </h6>
              <p className="fw-semibold text-danger mb-0">
                ₹{trip?.totalAmount?.toFixed(2) || "0.00"}
              </p>
          </div>
         <div>
            <p className="text-muted mb-1">Authorized Signature</p>
            <div
              style={{
                width: "150px",
                height: "1px",
                backgroundColor: "#ccc",
                float: "right",
                marginTop: "30px",
              }}
            ></div>
         </div>
        </div>
      </Modal.Body>

      <Modal.Footer>
        <Button variant="secondary" onClick={handleClose}>
          Close
        </Button>
        <Button
          onClick={handleDownloadPDF}
          style={{
            backgroundColor: "#18575A",
            border: "none",
            display: "flex",
            alignItems: "center",
            gap: "5px",
          }}
        >
          <FaDownload /> Download PDF
        </Button>
      </Modal.Footer>
    </Modal>
  );
};

export default InvoiceMaster;
